spring:
  application:
    name: aws-deployment
  datasource:
    url: jdbc:mysql://database-1.cbomkky48odn.eu-north-1.rds.amazonaws.com:3306/myprodDb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: Buvi2903
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8097
